version: "3"

services:
  service1:
    container_name: service1
    build:
      context: ./service1
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - /app/dist
      - ./service1:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5000:5000"

  service2:
    container_name: service2
    build:
      context: ./service2
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - /app/dist
      - ./service2:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5001:5000"

  service3:
    container_name: service3
    build:
      context: ./service3
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - /app/dist
      - ./service3:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5002:5000"
