version: "3"

services:
  service1:
    container_name: service1
    build:
      context: ./service1
      dockerfile: Dockerfile
  service2:
    container_name: service2
    build:
      context: ./service2
      dockerfile: Dockerfile
  service3:
    container_name: service3
    build:
      context: ./service3
      dockerfile: Dockerfile
