version: "3"

services:
  redis:
    container_name: redis
    image: "redis:latest"

  # postgres:
  #   container_name: postgres
  #   image: "postgres:latest"
  #   environment:
  #     POSTGRES_HOST_AUTH_METHOD: trust

  service1:
    container_name: service1
    build:
      context: ./service1
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - /app/dist
      - ./service1:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    ports:
      - "5000:5000"
    depends_on:
      - redis

  # service2:
  #   container_name: service2
  #   build:
  #     context: ./service2
  #     dockerfile: Dockerfile
  #   volumes:
  #     - /app/node_modules
  #     - /app/dist
  #     - ./service2:/app
  #   environment:
  #     CHOKIDAR_USEPOLLING: 'true'
  #     PGUSER: 'postgres'
  #     PGHOST: 'postgres'
  #     PGDATABASE: 'postgres'
  #     PGPASSWORD: 'postgres'
  #     PGPORT: 5432
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - postgres

  # service3:
  #   container_name: service3
  #   build:
  #     context: ./service3
  #     dockerfile: Dockerfile
  #   volumes:
  #     - /app/node_modules
  #     - /app/dist
  #     - ./service3:/app
  #   environment:
  #     CHOKIDAR_USEPOLLING: 'true'
  #   ports:
  #     - "5000:5000"

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
    links:
      - service1
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    tty: true
